/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as VehicleRouteImport } from './routes/vehicle'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmergencyContactRouteImport } from './routes/emergency-contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardVehiclesRouteImport } from './routes/dashboard.vehicles'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAlertsRouteImport } from './routes/dashboard.alerts'
import { Route as ApiAuthSignupRouteImport } from './routes/api.auth.signup'
import { Route as ApiAuthProfileVehicleRouteImport } from './routes/api.auth.profile.vehicle'
import { Route as ApiAuthProfileEmergencyRouteImport } from './routes/api.auth.profile.emergency'
import { Route as ApiAuthOtpVerifyRouteImport } from './routes/api.auth.otp.verify'
import { Route as ApiAuthOtpSendRouteImport } from './routes/api.auth.otp.send'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleRoute = VehicleRouteImport.update({
  id: '/vehicle',
  path: '/vehicle',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyContactRoute = EmergencyContactRouteImport.update({
  id: '/emergency-contact',
  path: '/emergency-contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVehiclesRoute = DashboardVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProfileVehicleRoute = ApiAuthProfileVehicleRouteImport.update({
  id: '/api/auth/profile/vehicle',
  path: '/api/auth/profile/vehicle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProfileEmergencyRoute = ApiAuthProfileEmergencyRouteImport.update({
  id: '/api/auth/profile/emergency',
  path: '/api/auth/profile/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthOtpVerifyRoute = ApiAuthOtpVerifyRouteImport.update({
  id: '/api/auth/otp/verify',
  path: '/api/auth/otp/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthOtpSendRoute = ApiAuthOtpSendRouteImport.update({
  id: '/api/auth/otp/send',
  path: '/api/auth/otp/send',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/emergency-contact': typeof EmergencyContactRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vehicle': typeof VehicleRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/vehicles': typeof DashboardVehiclesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/auth/otp/send': typeof ApiAuthOtpSendRoute
  '/api/auth/otp/verify': typeof ApiAuthOtpVerifyRoute
  '/api/auth/profile/emergency': typeof ApiAuthProfileEmergencyRoute
  '/api/auth/profile/vehicle': typeof ApiAuthProfileVehicleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/emergency-contact': typeof EmergencyContactRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vehicle': typeof VehicleRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/vehicles': typeof DashboardVehiclesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/auth/otp/send': typeof ApiAuthOtpSendRoute
  '/api/auth/otp/verify': typeof ApiAuthOtpVerifyRoute
  '/api/auth/profile/emergency': typeof ApiAuthProfileEmergencyRoute
  '/api/auth/profile/vehicle': typeof ApiAuthProfileVehicleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/emergency-contact': typeof EmergencyContactRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vehicle': typeof VehicleRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/vehicles': typeof DashboardVehiclesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/auth/otp/send': typeof ApiAuthOtpSendRoute
  '/api/auth/otp/verify': typeof ApiAuthOtpVerifyRoute
  '/api/auth/profile/emergency': typeof ApiAuthProfileEmergencyRoute
  '/api/auth/profile/vehicle': typeof ApiAuthProfileVehicleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/emergency-contact'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/vehicle'
    | '/verify'
    | '/welcome'
    | '/dashboard/alerts'
    | '/dashboard/analytics'
    | '/dashboard/history'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/vehicles'
    | '/dashboard/'
    | '/api/auth/signup'
    | '/api/auth/otp/send'
    | '/api/auth/otp/verify'
    | '/api/auth/profile/emergency'
    | '/api/auth/profile/vehicle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/emergency-contact'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/vehicle'
    | '/verify'
    | '/welcome'
    | '/dashboard/alerts'
    | '/dashboard/analytics'
    | '/dashboard/history'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/vehicles'
    | '/dashboard'
    | '/api/auth/signup'
    | '/api/auth/otp/send'
    | '/api/auth/otp/verify'
    | '/api/auth/profile/emergency'
    | '/api/auth/profile/vehicle'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/emergency-contact'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/vehicle'
    | '/verify'
    | '/welcome'
    | '/dashboard/alerts'
    | '/dashboard/analytics'
    | '/dashboard/history'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/vehicles'
    | '/dashboard/'
    | '/api/auth/signup'
    | '/api/auth/otp/send'
    | '/api/auth/otp/verify'
    | '/api/auth/profile/emergency'
    | '/api/auth/profile/vehicle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EmergencyContactRoute: typeof EmergencyContactRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VehicleRoute: typeof VehicleRoute
  VerifyRoute: typeof VerifyRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiAuthOtpSendRoute: typeof ApiAuthOtpSendRoute
  ApiAuthOtpVerifyRoute: typeof ApiAuthOtpVerifyRoute
  ApiAuthProfileEmergencyRoute: typeof ApiAuthProfileEmergencyRoute
  ApiAuthProfileVehicleRoute: typeof ApiAuthProfileVehicleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle': {
      id: '/vehicle'
      path: '/vehicle'
      fullPath: '/vehicle'
      preLoaderRoute: typeof VehicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency-contact': {
      id: '/emergency-contact'
      path: '/emergency-contact'
      fullPath: '/emergency-contact'
      preLoaderRoute: typeof EmergencyContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vehicles': {
      id: '/dashboard/vehicles'
      path: '/vehicles'
      fullPath: '/dashboard/vehicles'
      preLoaderRoute: typeof DashboardVehiclesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/alerts': {
      id: '/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/profile/vehicle': {
      id: '/api/auth/profile/vehicle'
      path: '/api/auth/profile/vehicle'
      fullPath: '/api/auth/profile/vehicle'
      preLoaderRoute: typeof ApiAuthProfileVehicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/profile/emergency': {
      id: '/api/auth/profile/emergency'
      path: '/api/auth/profile/emergency'
      fullPath: '/api/auth/profile/emergency'
      preLoaderRoute: typeof ApiAuthProfileEmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/otp/verify': {
      id: '/api/auth/otp/verify'
      path: '/api/auth/otp/verify'
      fullPath: '/api/auth/otp/verify'
      preLoaderRoute: typeof ApiAuthOtpVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/otp/send': {
      id: '/api/auth/otp/send'
      path: '/api/auth/otp/send'
      fullPath: '/api/auth/otp/send'
      preLoaderRoute: typeof ApiAuthOtpSendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardVehiclesRoute: typeof DashboardVehiclesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardVehiclesRoute: DashboardVehiclesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EmergencyContactRoute: EmergencyContactRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VehicleRoute: VehicleRoute,
  VerifyRoute: VerifyRoute,
  WelcomeRoute: WelcomeRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiAuthOtpSendRoute: ApiAuthOtpSendRoute,
  ApiAuthOtpVerifyRoute: ApiAuthOtpVerifyRoute,
  ApiAuthProfileEmergencyRoute: ApiAuthProfileEmergencyRoute,
  ApiAuthProfileVehicleRoute: ApiAuthProfileVehicleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
